# Generated by Django 4.2.9 on 2024-03-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
