name: Docker Image CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_REPO: bloodfan/django-chat

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
  push:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: .
          tags: ${{ env.DOCKER_IMAGE_REPO }}:latest
          file: docker/prod/web/Dockerfile

  deploy:
    needs: [push]
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}

    - name: Delete old files
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
        script: |
          cd /home/tester-v1/django-chat
          docker compose -f prod.yml down
          docker image prune -a -f

    - name: Copy Docker Compose file to server
      uses: appleboy/scp-action@v0.0.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
        source: 'prod.yml'
        target: '/home/tester-v1/django-chat/'

    - name: Copy docker folder to server
      uses: appleboy/scp-action@v0.0.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
        source: 'docker/*'
        target: '/home/tester-v1/django-chat/'

    - name: Deploy with Docker Compose
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_PRIVATE_SSH_KEY }}
        script: |
          cd /home/tester-v1/django-chat
          docker compose -f prod.yml up -d --build
